In [6]:
import torch
MLP = torch.nn.Linear(in_features=3, out_features=1)
data = torch.rand(size=(3,2,3))
print(data)
print(MLP.forward(data))

tensor([[[0.8903, 0.3637, 0.2271],
         [0.1411, 0.1474, 0.4463]],

        [[0.5119, 0.6947, 0.1550],
         [0.8227, 0.8504, 0.6307]],

        [[0.8054, 0.3368, 0.6048],
         [0.7877, 0.9162, 0.5057]]])
tensor([[[0.9499],
         [0.7141]],

        [[0.9082],
         [1.2928]],

        [[1.0857],
         [1.2471]]], grad_fn=<ViewBackward0>)


In [10]:
a = torch.randint(low=0,high=10,size=(2,3,4))
print(a)
b = torch.randint(low=0,high=10,size=(2,1,4))
print(b)
print(a*b)

tensor([[[3, 6, 7, 7],
         [0, 7, 5, 8],
         [9, 9, 1, 0]],

        [[1, 6, 1, 3],
         [7, 3, 4, 7],
         [4, 7, 1, 7]]])
tensor([[[0, 9, 6, 3]],

        [[5, 9, 6, 4]]])
tensor([[[ 0, 54, 42, 21],
         [ 0, 63, 30, 24],
         [ 0, 81,  6,  0]],

        [[ 5, 54,  6, 12],
         [35, 27, 24, 28],
         [20, 63,  6, 28]]])
